import { StyleSheet } from 'react-native';
import {
  border,
  brand,
  elevation,
  fontSize,
  fontWeight,
  motion,
  neutral,
  palette,
  radii,
  spacing,
  surface,
  text,
  typography,
} from '@/src/shared/theme';

export const styles = StyleSheet.create({
  center: {
    alignItems: 'center',
    flex: 1,
    gap: 12,
    justifyContent: 'center',
  },
  header: {
    gap: spacing[2],
    paddingBottom: spacing[3],
  },
  dashboardLink: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: spacing[1],
    minHeight: 44,
    paddingVertical: spacing[2],
  },
  dashboardLinkText: {
    color: brand[700],
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
  },
  headerTitleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: spacing[3],
  },
  eyebrow: {
    color: text.muted,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  title: {
    color: text.primary,
    flex: 1,
    ...typography.sectionTitle,
  },
  progress: {
    backgroundColor: surface.active,
    borderRadius: radii.full,
    color: text.brand,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    overflow: 'hidden',
    paddingHorizontal: spacing[2],
    paddingVertical: spacing[1],
  },
  overviewCard: {
    backgroundColor: surface.subtle,
    borderColor: border.default,
    borderRadius: radii['2xl'],
    borderWidth: 1,
    gap: spacing[2],
    marginBottom: spacing[4],
    padding: spacing[4],
  },
  overviewLabel: {
    color: text.brand,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    textTransform: 'uppercase',
  },
  overviewValue: {
    color: text.primary,
    fontSize: fontSize['2xl'],
    fontWeight: fontWeight.bold,
  },
  card: {
    backgroundColor: surface.card,
    borderColor: border.default,
    borderRadius: radii['2xl'],
    borderWidth: 1,
    gap: spacing[4],
    marginBottom: spacing[4],
    padding: spacing[4],
    ...elevation.raised,
  },
  cardTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  itemLabel: {
    color: text.muted,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    textTransform: 'uppercase',
  },
  audioMetaRow: {
    alignItems: 'flex-end',
    gap: 2,
  },
  audioMeta: {
    color: text.secondary,
    fontSize: fontSize.sm,
    textAlign: 'right',
  },
  runnerLayout: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: spacing[4],
  },
  audioDock: {
    backgroundColor: surface.card,
    borderColor: border.default,
    borderRadius: radii['2xl'],
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing[2],
    marginBottom: spacing[4],
    padding: spacing[2],
  },
  audioDockBook: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    flexWrap: 'nowrap',
    marginBottom: spacing[3],
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  modeButton: {
    alignItems: 'center',
    backgroundColor: surface.card,
    borderColor: 'transparent',
    borderRadius: radii.xl,
    borderWidth: 1,
    flexDirection: 'row',
    flexGrow: 1,
    gap: spacing[2],
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 104,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
  },
  modeButtonBook: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    flexDirection: 'column',
    gap: spacing[1],
    minWidth: 0,
    paddingHorizontal: spacing[1],
  },
  modeButtonActive: {
    backgroundColor: palette.primaryStrong,
    borderColor: palette.primaryStrong,
    ...elevation.focus,
  },
  modeButtonText: {
    color: brand[700],
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
  },
  modeButtonTextActive: {
    color: neutral[0],
  },
  modeButtonTextBook: {
    color: text.secondary,
    fontSize: fontSize.lg,
    textAlign: 'center',
  },
  modeButtonTextBookSelected: {
    color: text.brand,
  },
  modeSelectionDot: {
    backgroundColor: brand[700],
    borderRadius: radii.full,
    height: 6,
    width: 6,
  },
  audioIconButtonDisabled: {
    opacity: 0.45,
  },
  audioIconButtonPressed: {
    opacity: motion.pressedOpacity,
  },
  notice: {
    backgroundColor: surface.active,
    borderRadius: radii.lg,
    color: text.brand,
    fontSize: fontSize.base,
    padding: spacing[3],
  },
  syncError: {
    backgroundColor: palette.warningSurface,
    borderRadius: radii.lg,
    color: text.warning,
    fontSize: fontSize.base,
    marginBottom: spacing[3],
    padding: spacing[3],
  },
  navigationRow: {
    gap: spacing[2],
    marginBottom: spacing[4],
  },
  meta: {
    color: text.secondary,
    fontSize: fontSize.base,
  },
  error: {
    color: text.error,
    textAlign: 'center',
  },
});
