import { StyleSheet } from 'react-native';
import {
  border,
  brand,
  elevation,
  fontSize,
  fontWeight,
  motion,
  radii,
  spacing,
  surface,
  text,
} from '@/src/shared/theme';

export const pagedStyles = StyleSheet.create({
  content: {
    flex: 1,
    gap: spacing[3],
    paddingBottom: spacing[4],
  },
  bookCard: {
    backgroundColor: surface.card,
    borderColor: border.default,
    borderRadius: radii['3xl'],
    borderWidth: 1,
    flex: 1,
    minHeight: 390,
    overflow: 'hidden',
    paddingHorizontal: spacing[5],
    paddingVertical: spacing[4],
    ...elevation.raised,
  },
  bookHeader: {
    alignItems: 'center',
  },
  bookIcon: {
    alignItems: 'center',
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  sentenceViewport: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    minHeight: 190,
    paddingHorizontal: spacing[1],
    paddingVertical: spacing[4],
    width: '100%',
  },
  sentencePage: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  notice: {
    color: text.brand,
    fontSize: fontSize.sm,
    marginBottom: spacing[2],
    textAlign: 'center',
  },
  playbackSection: {
    gap: spacing[2],
  },
  progressTrack: {
    backgroundColor: surface.active,
    borderRadius: radii.full,
    height: 7,
    overflow: 'visible',
    position: 'relative',
  },
  progressFill: {
    backgroundColor: brand[700],
    borderRadius: radii.full,
    bottom: 0,
    left: 0,
    position: 'absolute',
    top: 0,
  },
  progressThumb: {
    backgroundColor: brand[700],
    borderColor: surface.card,
    borderRadius: radii.full,
    borderWidth: 2,
    height: 20,
    marginLeft: -10,
    marginTop: -7,
    position: 'absolute',
    top: 0,
    width: 20,
  },
  timeRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timeText: {
    color: text.secondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
  },
  controlRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: spacing[2],
  },
  sentenceButton: {
    alignItems: 'center',
    borderRadius: radii.full,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  sentenceButtonPressed: {
    backgroundColor: surface.active,
    opacity: motion.pressedOpacity,
  },
  sentenceButtonDisabled: {
    opacity: motion.disabledOpacity,
  },
  playButton: {
    alignItems: 'center',
    backgroundColor: brand[700],
    borderRadius: radii.full,
    height: 72,
    justifyContent: 'center',
    width: 72,
    ...elevation.focus,
  },
  playButtonPressed: {
    opacity: motion.pressedOpacity,
    transform: [{ scale: 0.98 }],
  },
  playButtonDisabled: {
    opacity: motion.disabledOpacity,
  },
  sentenceCount: {
    color: text.secondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    marginTop: spacing[2],
    textAlign: 'center',
  },
  syncError: {
    backgroundColor: surface.subtle,
    borderRadius: radii.lg,
    color: text.warning,
    fontSize: fontSize.sm,
    padding: spacing[2],
    textAlign: 'center',
  },
});
