import { StyleSheet } from 'react-native';
import {
  border,
  brand,
  fontSize,
  fontWeight,
  neutral,
  radii,
  surface,
  text,
} from '@/src/shared/theme';

export const styles = StyleSheet.create({
  center: {
    alignItems: 'center',
    flex: 1,
    gap: 12,
    justifyContent: 'center',
  },
  header: {
    marginBottom: 10,
  },
  title: {
    color: text.primary,
    fontSize: fontSize['4xl'],
    fontWeight: fontWeight.bold,
    marginBottom: 4,
  },
  meta: {
    color: text.secondary,
    fontSize: fontSize.md,
    lineHeight: 20,
  },
  syncMeta: {
    color: text.brand,
    fontSize: fontSize.sm,
    marginTop: 6,
  },
  error: {
    color: text.error,
    fontSize: fontSize.md,
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: brand[700],
    borderRadius: radii.md,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  retryText: {
    color: neutral[0],
    fontWeight: fontWeight.semibold,
  },
  summaryRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 14,
  },
  summaryCard: {
    backgroundColor: surface.card,
    borderColor: border.subtle,
    borderRadius: radii.xl,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  summaryValue: {
    color: text.brand,
    fontSize: fontSize['2xl'],
    fontWeight: fontWeight.bold,
  },
  summaryLabel: {
    color: text.muted,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    marginTop: 2,
  },
  searchInput: {
    backgroundColor: surface.input,
    borderColor: border.default,
    borderRadius: radii.lg,
    borderWidth: 1,
    color: text.primary,
    fontSize: fontSize.md,
    marginBottom: 12,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  listContent: {
    gap: 10,
    paddingBottom: 24,
  },
  lessonCard: {
    alignItems: 'center',
    backgroundColor: surface.card,
    borderColor: border.default,
    borderRadius: radii['2xl'],
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 76,
    padding: 16,
  },
  lessonCardCopy: {
    flex: 1,
    gap: 4,
  },
  lessonTitle: {
    color: text.primary,
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
  },
  lessonMeta: {
    color: text.secondary,
    fontSize: fontSize.base,
  },
  archiveButton: {
    alignItems: 'center',
    backgroundColor: brand[50],
    borderColor: brand[200],
    borderRadius: radii['2xl'],
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
    padding: 16,
  },
  archiveButtonTitle: {
    color: text.brand,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
  },
  archiveButtonMeta: {
    color: text.secondary,
    fontSize: fontSize.sm,
    marginTop: 2,
  },
  buttonPressed: {
    opacity: 0.72,
  },
  viewRoot: {
    flex: 1,
  },
  viewHeader: {
    marginBottom: 14,
  },
  backButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 2,
    marginBottom: 10,
    minHeight: 36,
  },
  backButtonText: {
    color: text.brand,
    fontSize: fontSize.md,
    fontWeight: fontWeight.semibold,
  },
  lessonViewTitle: {
    color: text.primary,
    fontSize: fontSize['3xl'],
    fontWeight: fontWeight.bold,
    marginBottom: 4,
  },
  progressTrack: {
    backgroundColor: neutral[200],
    borderRadius: radii.full,
    height: 7,
    marginTop: 14,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: brand[600],
    borderRadius: radii.full,
    height: '100%',
  },
  progressText: {
    color: text.secondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    marginTop: 6,
  },
  reviewList: {
    gap: 12,
    paddingBottom: 24,
  },
  reviewRow: {
    backgroundColor: surface.card,
    borderColor: border.default,
    borderRadius: radii['2xl'],
    borderWidth: 1,
    padding: 14,
  },
  reviewRowRevealed: {
    borderColor: brand[300],
    boxShadow: '0px 5px 16px rgba(8, 145, 178, 0.12)',
  },
  dictionaryTextRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
    minHeight: 64,
  },
  reviewColumn: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  columnLabel: {
    color: text.muted,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    marginBottom: 5,
    textTransform: 'uppercase',
  },
  dictionaryEnglish: {
    color: text.primary,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    lineHeight: 22,
  },
  dictionaryDivider: {
    alignSelf: 'stretch',
    backgroundColor: border.default,
    width: 1,
  },
  translationReveal: {
    borderRadius: radii.md,
  },
  dictionaryTranslation: {
    color: text.brand,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    lineHeight: 22,
  },
  dictionaryTranslationHidden: {
    color: neutral[300],
    fontSize: 13,
    letterSpacing: 1,
    lineHeight: 22,
  },
  rowFooter: {
    alignItems: 'center',
    borderTopColor: border.subtle,
    borderTopWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    paddingTop: 10,
  },
  audioActions: {
    flexDirection: 'row',
    gap: 8,
  },
  iconAction: {
    alignItems: 'center',
    backgroundColor: brand[50],
    borderRadius: radii.full,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  streakText: {
    color: text.secondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
  },
  decisionRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 12,
  },
  againButton: {
    alignItems: 'center',
    backgroundColor: '#fff7ed',
    borderColor: '#fed7aa',
    borderRadius: radii.lg,
    borderWidth: 1,
    flex: 1,
    minHeight: 46,
    justifyContent: 'center',
  },
  againButtonText: {
    color: '#c2410c',
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
  },
  knowButton: {
    alignItems: 'center',
    backgroundColor: brand[700],
    borderRadius: radii.lg,
    flex: 1,
    minHeight: 46,
    justifyContent: 'center',
  },
  knowButtonText: {
    color: neutral[0],
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
  },
  completionCard: {
    alignItems: 'center',
    backgroundColor: surface.card,
    borderColor: brand[200],
    borderRadius: radii['2xl'],
    borderWidth: 1,
    gap: 8,
    marginTop: 28,
    padding: 24,
  },
  completionTitle: {
    color: text.primary,
    fontSize: fontSize['2xl'],
    fontWeight: fontWeight.bold,
    textAlign: 'center',
  },
  primaryAction: {
    alignItems: 'center',
    backgroundColor: brand[700],
    borderRadius: radii.lg,
    marginTop: 8,
    minHeight: 46,
    paddingHorizontal: 20,
    justifyContent: 'center',
  },
  primaryActionText: {
    color: neutral[0],
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
  },
  archiveList: {
    gap: 12,
    paddingBottom: 24,
  },
  archiveSection: {
    backgroundColor: surface.card,
    borderColor: border.default,
    borderRadius: radii['2xl'],
    borderWidth: 1,
    gap: 2,
    padding: 14,
  },
  archiveSectionTitle: {
    color: text.primary,
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    marginBottom: 6,
  },
  archiveRow: {
    alignItems: 'center',
    borderTopColor: border.subtle,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 12,
  },
  archiveRowCopy: {
    flex: 1,
    gap: 3,
  },
  archiveTranslation: {
    color: text.brand,
    fontSize: fontSize.md,
    fontWeight: fontWeight.semibold,
  },
  restoreButton: {
    backgroundColor: brand[50],
    borderColor: brand[200],
    borderRadius: radii.md,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  restoreButtonText: {
    color: text.brand,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
  },
  emptyCard: {
    alignItems: 'center',
    backgroundColor: surface.card,
    borderColor: border.default,
    borderRadius: radii.lg,
    borderWidth: 1,
    padding: 18,
  },
  emptyTitle: {
    color: text.primary,
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    marginBottom: 4,
    textAlign: 'center',
  },
  emptyText: {
    color: text.secondary,
    fontSize: fontSize.base,
    lineHeight: 20,
    textAlign: 'center',
  },
  loadingView: {
    alignItems: 'center',
    flex: 1,
    gap: 12,
    justifyContent: 'center',
  },
});
